development:
  adapter: postgres
  pool: 5
  timeout: 5000
  database: db/development.postgres

test:
  adapter: postgres
  pool: 5
  timeout: 5000
  database: db/test.postgres

production:
  adapter: postgres
  pool: 5
  timeout: 5000
  database: db/production.postgres
