development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: db/development

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: db/test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: db/production.postgres
